version: "3"

services:
  #loki:
  #  image: grafana/loki:latest
  #  container_name: loki
  #  expose:
  #    - "3100"
  #  networks:
  #    - ntw_logging
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - ntw_logging
  renderer:
    image: grafana/grafana-image-renderer
    container_name: grafana-image-renderer
    expose:
      - "8081"
    environment:
      ENABLE_METRICS: "true"
    networks:
      - ntw_logging
networks:
  ntw_logging:
    external: true