version: "3"

# docker run -d --name loki --restart unless-stopped -p 3100:3100 --network ntw_logging grafana/loki:latest "-config.file=/etc/loki/local-config.yaml"

services:
  loki:
    image: grafana/loki:master
    container_name: loki
    expose:
      - "3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - ntw_logging
  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - "3000:3000"
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - ntw_logging
  renderer:
    image: grafana/grafana-image-renderer
    container_name: grafana-image-renderer
    expose:
      - "8081"
    environment:
      ENABLE_METRICS: "true"
    networks:
      - ntw_logging
networks:
  ntw_logging:
    external: true