-- MySQL Script generated by MySQL Workbench
-- Sat No 28 00:00:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vendorcommanddb
-- -----------------------------------------------------
-- Base de datos que permite gestionar la informacion de vendors
DROP SCHEMA IF EXISTS `vendorcommanddb` ;

-- -----------------------------------------------------
-- Schema Products Command 
--
-- Base de datos que permite gestionar la informacion de vendors
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vendorcommanddb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;

USE `vendorcommanddb` ;

CREATE TABLE IF NOT EXISTS VENDORS (
    ID_PROVIDER   VARCHAR(512),
	NAME_PROVIDER VARCHAR(1000),
    NIT           VARCHAR(512),
    ID_TYPE       VARCHAR(512),
    ADDRESS       VARCHAR(1500),
	TELEPHONE     VARCHAR(1500),
	EMAIL         VARCHAR(1500),
	ID_COUNTRY    VARCHAR(1500),
	ID_PROVINCE   VARCHAR(1500),
	ID_CITY       VARCHAR(1500)
) ENGINE = InnoDB;

CREATE TABLE VENDOR_TYPES (
	TYPES_ID VARCHAR(512),
	DESCRIPTION VARCHAR(512)
) ENGINE = InnoDB;

ALTER TABLE VENDORS ADD CONSTRAINT PK_VDR PRIMARY KEY (ID_PROVIDER);
ALTER TABLE VENDOR_TYPES   ADD CONSTRAINT PK_TPS PRIMARY KEY (TYPES_ID);

ALTER TABLE VENDORS ADD CONSTRAINT FK_VDR_TPS FOREIGN KEY (ID_TYPE) REFERENCES VENDOR_TYPES (TYPES_ID);

ALTER TABLE VENDORS ADD INDEX(NAME_PROVIDER);