# -------------------------------------------------------------------
# - DOCKER COMPOSE FILE
# - AUTOR: Equipo 5
# - FECHA: 03-Octubre-2020
# - DESCRIPCION: Docker compose file que permite la
# -              creacion de 2 contendores uno para la aplicacion
# -              y otro para la base de datos de la app de seguridad
# -------------------------------------------------------------------

version: '3.7'

#x-logging: &logging
#    driver: loki
#    options:
#      loki-url: "http://loki:3100/loki/api/v1/push"

services:
  db_security:
    image: mysql:5.7.31
    container_name: db_security
    hostname: db_security
    restart: always
    #logging: *logging
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'securitydb'
      MYSQL_USER: 'security'
      MYSQL_PASSWORD: 'security2020++'
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    volumes:
      - ./scripts/security/mysql-security-schema-v0.1.sql:/docker-entrypoint-initdb.d/mysql-security-schema-v0.1.sql
      - data_security:/var/lib/mysql
    networks:
      - ntw_databases
  db_product_command:    
    image: mysql:5.7.31    
    container_name: db_product_command
    hostname: db_product_command
    restart: always
    #logging: *logging
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'productcommanddb'
      MYSQL_USER: 'product'
      MYSQL_PASSWORD: 'product2020++'
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3301:3306
    volumes:
      - ./scripts/products/command/mysql-products-command-schema-v0.1.sql:/docker-entrypoint-initdb.d/mysql-products-command-schema-v0.1.sql
      - data_product_command:/var/lib/mysql
    networks:
      - ntw_databases
      #- ntw_logging
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 180M
 
  db_product_query:    
    image: mysql:5.7.31    
    container_name: db_product_query
    hostname: db_product_query
    restart: always
    #logging: *logging
    environment:
      MYSQL_ROOT_PASSWORD: 'mysql'
      MYSQL_DATABASE: 'productquerydb'
      MYSQL_USER: 'product'
      MYSQL_PASSWORD: 'product2020++'
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3302:3306
    volumes:
      - ./scripts/products/query/mysql-products-query-schema-v0.1.sql:/docker-entrypoint-initdb.d/mysql-products-query-schema-v0.1.sql
      - data_product_query:/var/lib/mysql
    networks:
      - ntw_databases
      #- ntw_logging
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 180M    
volumes:
  data_security:
  data_product_command:
  data_product_query:
networks:
  ntw_databases:
    external: true
  #ntw_logging:
  #  external: true