-- MySQL Script generated by MySQL Workbench
-- Sat Oct 03 16:45:41 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema productquerydb
-- -----------------------------------------------------
-- Base de datos que permite controlar la seguridad para mis servicios rest
DROP SCHEMA IF EXISTS `productquerydb` ;

-- -----------------------------------------------------
-- Schema security
--
-- Base de datos que permite controlar la seguridad para mis servicios rest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `productquerydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `productquerydb` ;

CREATE TABLE IF NOT EXISTS PRODUCT_TYPE (
	ID_TYPE     VARCHAR(512),
	DESCRIPTION VARCHAR(512)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PRODUCTS (
	PRODUCT_CODE        VARCHAR(512),
    PRODUCT_NAME        VARCHAR(512),
    PRODUCT_DESCRIPTION VARCHAR(512),
    START_DATE          DATE,
    END_DATE            DATE,
    PRODUCT_TYPE_ID     VARCHAR(512),
    PRODUCT_PRICE       BIGINT,
    ORIGIN_CITY         VARCHAR(512),
    DESTINATION_CITY    VARCHAR(512),
	PRODUCT_IMAGE       VARCHAR(512),
    VENDOR_ID           VARCHAR(512)
) ENGINE = InnoDB;

ALTER TABLE PRODUCTS ADD CONSTRAINT PK_PRD PRIMARY KEY (PRODUCT_CODE);

ALTER TABLE PRODUCT_TYPE ADD CONSTRAINT PK_PRD_TP PRIMARY KEY (ID_TYPE);

ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRD_TYPE FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPE (ID_TYPE);

ALTER TABLE PRODUCTS ADD INDEX(PRODUCT_CODE);
ALTER TABLE PRODUCTS ADD INDEX(PRODUCT_NAME);
ALTER TABLE PRODUCTS ADD INDEX(PRODUCT_DESCRIPTION);

Alter table PRODUCTS ADD FULLTEXT (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_DESCRIPTION);