-- MySQL Script generated by MySQL Workbench
-- Sat Oct 07 00:00:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema productcommanddb
-- -----------------------------------------------------
-- Base de datos que permite gestionar la informacion de productos
DROP SCHEMA IF EXISTS `productcommanddb` ;

-- -----------------------------------------------------
-- Schema Products Command 
--
-- Base de datos que permite gestionar la informacion de productos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `productcommanddb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;

USE `productcommanddb` ;

CREATE TABLE IF NOT EXISTS PRODUCT_TYPE (
	ID_TYPE     VARCHAR(512),
	DESCRIPTION VARCHAR(512)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID          VARCHAR(512),
	PRODUCT_CODE        VARCHAR(512),
    PRODUCT_NAME        VARCHAR(512),
    PRODUCT_DESCRIPTION VARCHAR(512),
    START_DATE          DATE,
    END_DATE            DATE,
    PRODUCT_TYPE_ID     VARCHAR(30),
    PRODUCT_PRICE       BIGINT,	
    ORIGIN_CITY         VARCHAR(512),
    DESTINATION_CITY    VARCHAR(512),
    VENDOR_ID           VARCHAR(512)
) ENGINE = InnoDB;

ALTER TABLE PRODUCTS     ADD CONSTRAINT PK_PRD    PRIMARY KEY (PRODUCT_ID);
ALTER TABLE PRODUCT_TYPE ADD CONSTRAINT PK_PRD_TP PRIMARY KEY (ID_TYPE);

ALTER TABLE PRODUCTS ADD CONSTRAINT FK_PRD_TYPE FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPE (ID_TYPE);

ALTER TABLE PRODUCTS ADD INDEX(PRODUCT_CODE, PRODUCT_NAME, PRODUCT_DESCRIPTION);