-- MySQL Script generated by MySQL Workbench
-- Sat Oct 07 00:00:00 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema orderquerydb
-- -----------------------------------------------------
-- Base de datos que permite consultar la informacion de las ordenes
DROP SCHEMA IF EXISTS `orderquerydb` ;

-- -----------------------------------------------------
-- Schema Orders Command 
--
-- Base de datos que permite consultar la informacion de las ordenes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `orderquerydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;

USE `orderquerydb` ;

CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID      VARCHAR(512),
	ORDER_CODE	  VARCHAR(512),
    CUSTOMER_ID   VARCHAR(512),
    PAYMENT_ID    VARCHAR(512),
    STATUS 		  VARCHAR(512),
    CREATION_DATE DATE
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS PRODUCTBYORDERS (
	ORDER_ID      VARCHAR(512),
	PRODUCT_ID    VARCHAR(512),
	PRODUCT_CODE  VARCHAR(512),
	PRICE_PRODUCT BIGINT
) ENGINE = InnoDB;

ALTER TABLE ORDERS ADD CONSTRAINT PK_ORD PRIMARY KEY (ORDER_ID);
ALTER TABLE PRODUCTBYORDERS ADD CONSTRAINT PK_PRD_ORD PRIMARY KEY (ORDER_ID, PRODUCT_ID);

ALTER TABLE PRODUCTBYORDERS ADD CONSTRAINT FK_PRD_ODR FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID);

ALTER TABLE ORDERS ADD INDEX(ORDER_CODE);
ALTER TABLE PRODUCTBYORDERS ADD INDEX(ORDER_ID);
ALTER TABLE PRODUCTBYORDERS ADD INDEX(PRODUCT_CODE);