global:
    scrape_interval: 5s # How frequently to scrape targets by default
  
scrape_configs:
    - job_name: 'toures-balon'                      # The job name is assigned to scraped metrics by default.
      metrics_path: '/monitor/actuator/prometheus'  # The HTTP resource path on which to fetch metrics from targets.
      scrape_interval: 5s                           # How frequently to scrape targets from this job.
      static_configs:                               # A static_config allows specifying a list of targets and a common label set for them
        - targets: ['192.168.20.20:6190'] # server-config
        - targets: ['192.168.20.20:6191'] # server-eureka
        - targets: ['192.168.20.20:6192'] # server-gateway
        - targets: ['192.168.20.20:6150'] # server-security
        
        - targets: ['192.168.20.20:'] # image-command-services
        - targets: ['192.168.20.20:'] # image-query-services
        
        - targets: ['192.168.20.20:'] # campaings-command-services
        - targets: ['192.168.20.20:'] # campaings-query-services
        
        - targets: ['192.168.20.20:'] # products-command-services
        - targets: ['192.168.20.20:'] # products-query-services
        
        - targets: ['192.168.20.20:'] # orders-command-services
        - targets: ['192.168.20.20:'] # orders-query-services
        
        #- targets: ['192.168.20.20:'] # providers-command-services
        #- targets: ['192.168.20.20:'] # providers-query-services
        
        - targets: ['192.168.20.20:6085'] # aa-query-services
        - targets: ['192.168.20.20:6086'] # avianca-query-services
        - targets: ['192.168.20.20:6091'] # bl-query-services
        - targets: ['192.168.20.20:6088'] # cc-query-services
        - targets: ['192.168.20.20:6092'] # dc-query-services
        - targets: ['192.168.20.20:6096'] # ht-query-services
        - targets: ['192.168.20.20:6097'] # paywoaint-query-services
        
        - targets: ['192.168.20.20:6097'] # bpm-command-services
        - targets: ['192.168.20.20:6097'] # notifications-services