global:
    scrape_interval: 5s # How frequently to scrape targets by default
  
scrape_configs:
    - job_name: 'toures-balon'                      # The job name is assigned to scraped metrics by default.
      metrics_path: '/monitor/actuator/prometheus'  # The HTTP resource path on which to fetch metrics from targets.
      scrape_interval: 5s                           # How frequently to scrape targets from this job.
      static_configs:                               # A static_config allows specifying a list of targets and a common label set for them
        - targets: ['10.39.1.85:6190'] # server-config
        - targets: ['10.39.1.85:6191'] # server-eureka
        - targets: ['10.39.1.85:6192'] # server-gateway
        - targets: ['10.39.1.85:6150'] # server-security        
        - targets: ['10.39.1.94:6083'] # image-command-services
        - targets: ['10.39.1.94:6084'] # image-query-services        
        - targets: ['10.39.1.94:6087'] # campaings-command-services
        - targets: ['10.39.1.94:6088'] # campaings-query-services        
        - targets: ['10.39.1.94:6081'] # products-command-services
        - targets: ['10.39.1.94:6082'] # products-query-services        
        - targets: ['10.39.1.94:6089'] # orders-command-services
        - targets: ['10.39.1.94:6090'] # orders-query-services        
        - targets: ['10.39.1.94:6094'] # providers-command-services
        - targets: ['10.39.1.94:6095'] # providers-query-services        
        - targets: ['10.39.1.94:6085'] # aa-query-services
        - targets: ['10.39.1.94:6086'] # avianca-query-services
        - targets: ['10.39.1.94:6091'] # bl-query-services
        - targets: ['10.39.1.94:6098'] # cc-query-services
        - targets: ['10.39.1.94:6092'] # dc-query-services
        - targets: ['10.39.1.94:6096'] # ht-query-services
        - targets: ['10.39.1.94:6097'] # paywoaint-query-services        
        - targets: ['10.39.1.94:6099'] # bpm-command-services
        - targets: ['10.39.1.94:6093'] # notifications-services
        - targets: ['10.39.1.94:6100'] # vendors-command-services
        - targets: ['10.39.1.94:6101'] # vendors-query-services